### ISSUE TITLE
Decrements counter?

### ISSUE THREAD

**Issue by davidosomething** [rhysd/vim-operator-surround#29] opened 2016-03-30 15:17 UTC
```
<?php
    $sponsor_info  = array(
        'na|me'    => $promoter_info[0]->post_title,
        'content' => $promoter_info[0]->post_content,
    );
```

cursor at the `|`, surround replace around `'` with `"` (switch to double quote) causes the `[0]` to decrement (like `C-x`) (using recommended mapping and keys: `sra'"`

**Comment by rhysd** [comment] 2017-10-06 03:46
I'm closing this because it is not reproducible now. If someone sees this problem, please let me know by commenting here.

**Closed by rhysd** 2017-10-06 03:46 UTC
